<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6jq5k95\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6jq5k95/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6jq5k95.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6jq5k95\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6jq5k95\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6jq5k95',
    'container.build_id' => '36174560',
    'container.build_time' => 1564996231,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6jq5k95');
