<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.O7_3mU4' shared service.

return $this->privates['.service_locator.O7_3mU4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'profilRepository' => ['privates', 'App\\Repository\\ProfilRepository', 'getProfilRepositoryService.php', true],
], [
    'profilRepository' => 'App\\Repository\\ProfilRepository',
]);
