<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.EGRfUSe' shared service.

return $this->privates['.service_locator.EGRfUSe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'retrait' => ['privates', '.errored..service_locator.EGRfUSe.App\\Entity\\Retrait', NULL, 'Cannot autowire service ".service_locator.EGRfUSe": it references class "App\\Entity\\Retrait" but no such service exists.'],
], [
    'retrait' => 'App\\Entity\\Retrait',
]);
