<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.GCHC3nQ.App\Entity\Envoi' shared service.

include_once $this->targetDirs[3].'/src/Entity/Envoi.php';

return $this->privates['.errored..service_locator.GCHC3nQ.App\\Entity\\Envoi'] = new \App\Entity\Envoi();
