<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GCHC3nQ' shared service.

return $this->privates['.service_locator.GCHC3nQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'envoi' => ['privates', '.errored..service_locator.GCHC3nQ.App\\Entity\\Envoi', NULL, 'Cannot autowire service ".service_locator.GCHC3nQ": it references class "App\\Entity\\Envoi" but no such service exists.'],
], [
    'envoi' => 'App\\Entity\\Envoi',
]);
