<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.LH1zOZf' shared service.

return $this->privates['.service_locator.LH1zOZf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'envoiRepository' => ['privates', 'App\\Repository\\EnvoiRepository', 'getEnvoiRepositoryService.php', true],
], [
    'envoiRepository' => 'App\\Repository\\EnvoiRepository',
]);
