<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.thYJGNJ' shared service.

return $this->privates['.service_locator.thYJGNJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'retraitRepository' => ['privates', 'App\\Repository\\RetraitRepository', 'getRetraitRepositoryService.php', true],
], [
    'retraitRepository' => 'App\\Repository\\RetraitRepository',
]);
