<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.E3DK7HO' shared service.

return $this->privates['.service_locator.E3DK7HO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'depot' => ['privates', '.errored..service_locator.E3DK7HO.App\\Entity\\Depot', NULL, 'Cannot autowire service ".service_locator.E3DK7HO": it references class "App\\Entity\\Depot" but no such service exists.'],
], [
    'depot' => 'App\\Entity\\Depot',
]);
