<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.5Pep64u.App\Entity\CompteBancaire' shared service.

include_once $this->targetDirs[3].'/src/Entity/CompteBancaire.php';

return $this->privates['.errored..service_locator.5Pep64u.App\\Entity\\CompteBancaire'] = new \App\Entity\CompteBancaire();
