<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPEiT2jS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPEiT2jS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPEiT2jS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPEiT2jS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPEiT2jS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PEiT2jS',
    'container.build_id' => 'ed6631ef',
    'container.build_time' => 1565008914,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPEiT2jS');
